version: '3.8'

services:
  
  frontend:
    build:
      context: ./
      dockerfile: Frontend/Dockerfile
    ports:
      - 51001:8080
    networks:
      - frontend
    depends_on: 
     - service.draw
      
  service.draw:
    build:
      context: ./
      dockerfile: DrawService/Dockerfile
    networks:
      - frontend
      - backend
  
  database.draw:
    build:
      context: ./DrawService/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

networks:
  frontend:
  backend: