version: '3.8'

services:
  
  frontend:
    build:
      context: ./
      dockerfile: Frontend/Dockerfile
    ports:
      - 51001:8080
    networks:
      - frontend
      - backend
    depends_on: 
     - service.draw
      
  
  service.draw:
    build:
      context: ./
      dockerfile: DrawService/Dockerfile
    networks:
      - backend

networks:
  frontend:
  backend: